# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('project_description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('address_link', models.CharField(max_length=150)),
                ('pdf_link', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=150)),
                ('testimony_quote', models.CharField(max_length=250)),
                ('image_1', models.CharField(max_length=200)),
                ('image_2', models.CharField(max_length=200)),
                ('image_3', models.CharField(max_length=200)),
                ('image_4', models.CharField(max_length=200)),
                ('image_5', models.CharField(max_length=200)),
                ('isIndustrial', models.BooleanField(default=False)),
                ('isAutomotive', models.BooleanField(default=False)),
                ('isInstitutional', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('resource_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_product_1', models.CharField(max_length=100)),
                ('featured_product_2', models.CharField(max_length=100)),
                ('featured_product_3', models.CharField(max_length=100)),
                ('featured_product_4', models.CharField(max_length=100)),
                ('featured_product_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=150)),
                ('article', models.CharField(max_length=650)),
                ('isFeatured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('image_1', models.CharField(max_length=200)),
                ('image_2', models.CharField(max_length=200)),
                ('image_3', models.CharField(max_length=200)),
                ('image_4', models.CharField(max_length=250)),
                ('image_5', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField(verbose_name='date updated')),
                ('product_description', models.CharField(max_length=200)),
                ('wattage', models.CharField(max_length=20)),
                ('lumens', models.CharField(max_length=20)),
                ('lumens_per_watt', models.CharField(max_length=20)),
                ('cct', models.CharField(max_length=30)),
                ('cri', models.CharField(max_length=20)),
                ('dimensions', models.CharField(max_length=30)),
                ('colors', models.CharField(max_length=40)),
                ('life_span', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=30)),
                ('replacement', models.CharField(max_length=30)),
                ('installation_info', models.CharField(max_length=25)),
                ('ul_certified', models.BooleanField(default=False)),
                ('dlc_certified', models.BooleanField(default=False)),
                ('isIndoor', models.BooleanField(default=False)),
                ('isOutdoor', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('check_1', models.CharField(max_length=25)),
                ('check_2', models.CharField(max_length=25)),
                ('check_3', models.CharField(max_length=25)),
                ('check_4', models.CharField(max_length=25)),
                ('check_5', models.CharField(max_length=25)),
                ('pdf_link', models.CharField(max_length=100)),
                ('pdf_preview', models.CharField(max_length=100)),
                ('ies_zip', models.CharField(max_length=100)),
                ('ies_name_1', models.CharField(max_length=100)),
                ('ies_link_1', models.CharField(max_length=100)),
                ('ies_name_2', models.CharField(max_length=100)),
                ('ies_link_2', models.CharField(max_length=100)),
                ('ies_name_3', models.CharField(max_length=100)),
                ('ies_link_3', models.CharField(max_length=100)),
                ('isAutomotive', models.CharField(max_length=25)),
                ('isInstitutional', models.CharField(max_length=25)),
                ('isAirport', models.CharField(max_length=25)),
                ('isHospital', models.CharField(max_length=25)),
                ('isHotel', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
