# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
