# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isAirport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isAutomotive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isHospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isHotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='isInstitutional',
            field=models.BooleanField(default=False),
        ),
    ]
